### ISSUE TITLE
Reorganising the BioJS community and team

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/organisation#1]
At the 2017 BOSC conference we had a Birds of a Feather (BoF) discussion about the future of BioJS.
Members of this discussion included among others: @CarlosHorro, @ljgarcia, @rowlandm, @yochannah, @bgruening, @sacdallago, @DennisSchwartz
Please feel free to add whoever I missed.

We discussed the current state of BioJS and shared some theories about how we got here (mostly lack of transparency and a central point of contact for new community members).
We decided to re-organise ourselves to keep BioJS alive, starting by taking stock of all the assets we have and centralising and spreading knowledge about things like infrastructure and domains.

We agreed to have regular calls to keep members of the core group up to date.

Please contribute to this issue anything that you think is important to keep BioJS moving. I'm looking forward to a lively discussion :)

**Comment by rowlandm** [comment]
Hi all,

Here are the minutes of the meeting at the BOF.
https://drive.google.com/open?id=1ctKJfQDAeYDBdf90DGnDeqEsYbWvs4jB07vRUdV3H0c

Regards,

Rowland

------------

Rowland Mosbergen | Business Manager, Stemformatics
Wells Laboratory | Centre for Stem Cell Systems
Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building
The University of Melbourne, Victoria 3010 Australia
T: +61 3 8344 6623 | E: rowland@stemformatics.org
W: www.stemformatics.org  | Skype: rowland.stemformatics

[image: id:image001.jpg@01D20A8D.3D4A4630]



This email and any attachments may contain personal information or
 information that is otherwise confidential or the subject of copyright.
Any use, disclosure or copying of any part of it is prohibited. The
University does not warrant that this email or any attachments are free
from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.



This email and any attachments may contain personal information or
 information that is otherwise confidential or the subject of copyright.
Any use, disclosure or copying of any part of it is prohibited. The
University does not warrant that this email or any attachments are free
from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.

**Comment by rowlandm** [comment]
Hi All,

The BioJS Community call will be on the 16th of August at 10am GMT+1.

Details are below. Zoom is the video conferencing tool that is free to
download and install.

https://docs.google.com/document/d/10RSevhuwtYRhBUUD5aakViwDPvOuaA_i4C652bn7oE4/edit#

Hope to see you all there!

Regards,

Rowland

Regards,

Rowland

------------

Rowland Mosbergen | Business Manager, Stemformatics
Wells Laboratory | Centre for Stem Cell Systems
Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building
The University of Melbourne, Victoria 3010 Australia
T: +61 3 8344 6623 | E: rowland@stemformatics.org
W: www.stemformatics.org  | Skype: rowland.stemformatics

[image: id:image001.jpg@01D20A8D.3D4A4630]



This email and any attachments may contain personal information or
 information that is otherwise confidential or the subject of copyright.
Any use, disclosure or copying of any part of it is prohibited. The
University does not warrant that this email or any attachments are free
from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.



This email and any attachments may contain personal information or
 information that is otherwise confidential or the subject of copyright.
Any use, disclosure or copying of any part of it is prohibited. The
University does not warrant that this email or any attachments are free
from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.
