### ISSUE TITLE
System architecture guideline for long term biojs.io

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#13]
1. One domain. Single server. MVC preferable.
2. Must be simple, maintainable and readable
2.1 From a specific url, it should be very easy to locate the code that is running that url and should be consistent eg. [fake example] http://biojs.io/contents/about_us should be in contents controller with about_us action. View would be in file contents/about_us and javascript would be contents/about_us.js etc.
2.2 Thin controllers and Fat models - so that the controllers provide an overview of what is being done.

**Comment by yochannah** [comment]
Expanding this description to make it easier for others to help out: 

[Biojs.io](http://biojs.io/) is a site that presents npm packages tagged biojs. There are certain limitations that mean we'd like to redesign it. In particular, the client driven implementation that is currently running can be very slow to load - probably related to the fact that there are over 100 biojs components and a lot of metadata associated with each component.

In order to fix this problem, we're planning to re-implement biojs.io in a performance-driven way, so that the client doesn't have to handle loading + rendering of hundreds of components at once, but instead it could store details about biojs components on a database and query them dynamically. For more details about this you can read [this comment](https://github.com/biojs/organisation/issues/9#issuecomment-346681810)

(@rowlandm / others: feel free to *edit* this comment if I'm mistaken. I'm trying to keep it short and simple for newcomers who might pick a task up, rather than a long discussion)
