### ISSUE TITLE
BioJS call August 2017

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/organisation#2]
There will be another online call to discuss the future of the BioJS project.
Please fill in the Doodle form here: 
https://doodle.com/poll/yxnnsk4edn78a42q
(Times are BST/UTC+1)

Hoping to see anyone who is interested in the future of BioJS joining!

@rowlandm please feel free to share the agenda document. I wasn't sure if that might be sensitive :)

**Comment by rowlandm** [comment]
Thanks Dennis!

Here is the agenda for the meeting:
https://drive.google.com/open?id=10RSevhuwtYRhBUUD5aakViwDPvOuaA_i4C652bn7oE4


Regards,

Rowland

------------

Rowland Mosbergen | Business Manager, Stemformatics
Wells Laboratory | Centre for Stem Cell Systems
Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building
The University of Melbourne, Victoria 3010 Australia
T: +61 3 8344 6623 | E: rowland@stemformatics.org
W: www.stemformatics.org  | Skype: rowland.stemformatics

[image: id:image001.jpg@01D20A8D.3D4A4630]



This email and any attachments may contain personal information or
 information that is otherwise confidential or the subject of copyright.
Any use, disclosure or copying of any part of it is prohibited. The
University does not warrant that this email or any attachments are free
from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.



This email and any attachments may contain personal information or
 information that is otherwise confidential or the subject of copyright.
Any use, disclosure or copying of any part of it is prohibited. The
University does not warrant that this email or any attachments are free
from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.

**Comment by rowlandm** [comment]
The date will be the 16th of August. The agenda is here:

https://drive.google.com/open?id=10RSevhuwtYRhBUUD5aakViwDPvOuaA_i4C652bn7oE4

Regards,

Rowland

------------

Rowland Mosbergen | Business Manager, Stemformatics
Wells Laboratory | Centre for Stem Cell Systems
Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building
The University of Melbourne, Victoria 3010 Australia
T: +61 3 8344 6623 | E: rowland@stemformatics.org
W: www.stemformatics.org  | Skype: rowland.stemformatics

[image: id:image001.jpg@01D20A8D.3D4A4630]



This email and any attachments may contain personal information or
 information that is otherwise confidential or the subject of copyright.
Any use, disclosure or copying of any part of it is prohibited. The
University does not warrant that this email or any attachments are free
from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.



This email and any attachments may contain personal information or
 information that is otherwise confidential or the subject of copyright.
Any use, disclosure or copying of any part of it is prohibited. The
University does not warrant that this email or any attachments are free
from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.
