### ISSUE TITLE
New homepage or temp placeholder

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#9]
biojs is down - see https://github.com/biojs/organisation/issues/8 
One possible temp solution that could become the long-term solution is to set up a placeholder gh-page homepage. This doesn't require any additional hosting or passwords beyond what we already have I think, so long as we can re-direct the domain to point to the new page.

Things to include as a minimum:
- explanation about what biojs is
- Link to biojs npm packages https://www.npmjs.com/search?q=biojs
- link to google groups: 
  - internal / contributor group: https://groups.google.com/forum/#!forum/biojavascript
  - external / public group: https://groups.google.com/forum/#!forum/biojs 
- link to gitter: https://gitter.im/biojs/biojs

**Comment by yochannah** [comment]
If you are interested in contributing to this issue please leave a comment!

**Comment by yochannah** [comment]
See also https://github.com/biojs/organisation/issues/4 for discussions of a possible design - but *any* basic page that we could point to would be better than a perfectly designed page right now while biojs is completely down

**Comment by ljgarcia** [comment]
+1 for the gh-pages solution
Quick question about Google groups, did not we say that we were moving all to GitHub issues? Are we keeping them at the end?

**Comment by yochannah** [comment]
We definitely discussed the option of doing so! I'm reluctant to completely close down the mailing groups - it might be easier for some to post to a mailing group than to a github issue, and I think we can't do without some email contact option. I don't mind monitoring the two groups for spam and queries in general.

**Comment by ljgarcia** [comment]
Thanks for the clarification regarding the lists. 
Now, about the github pages, how should we start? Anyone in particular looking at it? Will it be discussed during the next meeting?

**Comment by yochannah** [comment]
@xwatkins has indicated he might be able to help out...

**Comment by ljgarcia** [comment]
Great! I just gave @xwatkins permissions to create repos so we are advancing on this. It is a good start!

**Comment by ljgarcia** [comment]
Great! I just gave @xwatkins permissions to create repos so we are advancing on this. It is a good start!

**Comment by xwatkins** [comment]
Do you have a snapshot of the content of the old biojs.net? It would be great to have some kind of mission statement, and a few tiles (I think there was 3 or 4 like re-use, re-something...?!). Basically I need some content! 🙌

**Comment by yochannah** [comment]
Much like @DennisSchwartz, I had trouble recreating the biojs.net site locally - it seemed to be missing content compared to what was on the live site? 

The wayback machine version of biojs.net is probably our best bet for now: https://web.archive.org/web/20170723191208/http://biojs.net

**Comment by yochannah** [comment]
Oh, and @rowlandm has restored the mock he did last month: https://github.com/biojs/organisation/issues/4#issuecomment-345782470

**Comment by xwatkins** [comment]
Of course, wayback machine to the rescue! Should have something in the next couple of days

**Comment by DennisSchwartz** [comment]
@yochannah I actually managed to run it locally, the problem were that all the links don't seem to work.

~It's just a bad idea to run a static site compiled with Jekyll on top of Ghost. Just like duct taping stuff together haha.~

UPDATE: Actually not true.

**Comment by yochannah** [comment]
It's Jekyll *and* ghost? Oh my. Is the consensus that we shall have to abandon ghost and go full steam ahead with the gh-pages option? Add thumbs-up emojis or comment to indicate agreement. (Seems sanest to me not to require external resources when gh-pages can do it all).

**Comment by DennisSchwartz** [comment]
The only reason we were using Ghost was that Manny specifically asked us to have a CMS. So it seemed like an easy solution to just convert the site we had to a Ghost template.
I can take a look if we can just extract that into a gh-pages Jekyll site again.

@xwatkins Are you starting again from scratch? I'm sure your web dev skills are better than mine were two years ago 😄  but you still might wanna see if you can re-use some of the old code.

**Comment by DennisSchwartz** [comment]
One of the reasons I'm asking is, let's not hack something together quickly if we can somehow manage to get something up that gives us time to actually design what we would the new page to look like. Just a thought :)

**Comment by xwatkins** [comment]
I agree this should take a lot more thought and planning and probably be part of a strategy as a whole, so I was just going to quickly knock together a landing page for the project. As this is fairly simple as a first step I didn't think it was worth looking into using Jekyll / Ghost, although it doesn't mean we can't explore this later depending on requirements.

**Comment by DennisSchwartz** [comment]
Yeah that makes sense. 

Also, I have to take back my earlier statement. There is no Jekyll involved in this! It's a regular ghost theme with Handlebar templates. There is however, a lot of postinstall compiling with sass and ruby going on and I'm not sure why.

The bundler calls made me think it's Jekyll.

**Comment by rowlandm** [comment]
I'm happy with the gh option.

**Comment by xwatkins** [comment]
Ok, just pushed something very very basic based on old site and what I could gather from the thread above. Let me know if anything is missing/wrong etc...

**Comment by xwatkins** [comment]
Just noticed an issue in Firefox with the background SVG, will see if I can fix it.

**Comment by rowlandm** [comment]
Explore Components link doesn't work (pointing to www.biojs.io)



Regards,

*Rowland Mosbergen | Stemformatics Project Manager*

Centre for Stem Cell Systems

Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building

The University of Melbourne, Victoria 3010 Australia

*T: *+61 3 834 46623 *E: **rowland@stemformatics.org
<rowland@stemformatics.org>*

*I acknowledge the Wurundjeri people of the Kulin Nation as the Traditional
Owners of the land on which I work, and pay my respects to the Elders, past
and present.*



*[image: cid:image002.jpg@01D31D8F.E823DE70]*

 *CRICOS: 00116K*

This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The University
does not warrant that this email or any attachments are free from viruses
or defects. Please check any attachments for viruses and defects before
opening them. If this email is received in error, please delete it and
notify us by return email.

**Comment by xwatkins** [comment]
both fixed.

**Comment by 4ndr01d3** [comment]
Hey guys, sorry I missed the call.
So I'm wondering, what are the features that makes necessary a server for the registry? 
Isn't possible to create a client that gets info directly from npm and github and builds the registry on the fly?
Just an idea, BTW @xwatkins I'm happy to contribute coding, just let me know how can I help.

**Comment by DennisSchwartz** [comment]
@4ndr01d3 That's basically what's happening in the registry-workmen. But it's still a server-side issue. It's also needed for the examples.

So we need to create a proper discussion about the requirements of the BioJS website.

**Comment by 4ndr01d3** [comment]
@DennisSchwartz that's what I though, and from what I can see we can do all the workmen tasks on a js client, from the workmen README:

> 1. Search for all packages with a special tag on npm ('biojs', bionode') + remove duplicate packages (uniq)
> 2. Query npm -> package.json
> 3. Run extensions
> 3.1. npm: history stats
> 3.2. github
> 3.2.1. github info
> 3.2.2. github stats
> 3.2.3. Optional: Query github for snippets (ls "snippets")
> 4. Run post processing (e.g. removal of duplicate keywords)
> 5. Store the result in a DB
> 

From what I can see, most of this is to be able to provide more info on the list of components, and to be able to filter/search on it.
If we limit that list to what we get on [https://registry.npmjs.org/-/v1/search?text=keywords:biojs](https://registry.npmjs.org/-/v1/search?text=keywords:biojs) the rests can become queries to github when the "page" of the component is open. 
The snippets will require a bit of extra work, but I think the component page can be built on the fly.
Which makes me think the registry can be completely client based and therefore hosted completely on github pages.

Am I missing something?

**Comment by rowlandm** [comment]
Hey @4ndr01d3 

I hear what you are saying, we want to reduce our complexity and not have a server. But I think that due to the complexity of searching / snippets and our international audience we need to actually have a server to reduce complexity of the code and to provide a decent user experience (ie make it fast).

It's actually going to be very difficult to drive down complexity in this situation.

_Search for all packages with a special tag on npm ('biojs', bionode') + remove duplicate packages (uniq)_
This is an expensive query. You will be bringing back all the metadata needed across all packages and then filtering them on the client. This isn't scalable in the long term.

In Australia, we had issues with biojs.io taking ages to load and to add client processing on 500+ components in the future is going to be pretty intense. There are problems associated with things like dataTables when the number of rows is too high (pagination doesn't help) [[link](https://www.datatables.net/forums/discussion/comment/115481/)]

It's better to do this processing on the server into a DB. Cronjob every X minutes or so. Then when the user hit's the front page you get these aggregated views that are inexpensive to download. Then you can do a search via ajax and get back a cut down version of the components you have found.

This is a relatively basic website but perhaps you are right in that for the community this will be too advanced?  I get the feeling that the majority of the community is either new to Javascript and web development or are self-taught?

Perhaps we should discuss this in #13 ?

**Comment by rowlandm** [comment]
Has anyone looked at this in greater detail?

**Comment by yochannah** [comment]
ok, running some thoughts through my brain & I'm going to try to use this thread to discuss this further and sound out thoughts:

First: We have people volunteering to help out in gitter all the time but we don't have clear-cut tasks to give them. So, let's break our tasks into small do-able chunks with easy steps to get people started - but I need to understand better what we want.

@rowlandm, I know one of the big things, for you, is to make sure performance is better worldwide. Looking at the [workmen readme](https://github.com/biojs/registry-workmen) it seems that the workmen server probably does most of what we need without too much alteration - it fetches the packages via cronjob. Does that sound correct? 

As such I suggest the following tasks: 
- create a task to look into performance of the current app to find out if we can speed it up easily - this might be the easiest option if we are lucky. the workmen search endpoint has a search endpoint that allows you to limit result counts.
- task to convert your mock in HTML/CSS
- task to hook up web services to the mock

Does that sound sane and correct? If yes, I'll set up the tasks on github and tag them to attract newbies similar to this one: https://github.com/intermine/bluegenes/issues/197
